export const CATEGORIES = [
  "housing",
  "groceries",
  "household",
  "internet & mobile",
  "shopping",
  "personal care",
  "transport",
  "debt",
  "utilities",
  "health care",
  "entertainment",
  "savings",
  "other",
];
